elasticsearch:
  container_name: elasticsearch
  image: elasticsearch:2.4.4
  ports:
    - "9200:9200"
  environment:
    - "xpack.security.enabled=false"
  restart: always

logstash:
  container_name: logstash
  image: logstash:2.4.1
  links:
    - elasticsearch
    - rabbitmq
  volumes:
    - ./logstash.conf:/logstash.conf
  command: ["logstash", "agent", "-f", "/logstash.conf"]
  restart: always

kibana:
  container_name: kibana
  image: kibana:4.6.4
  links:
    - elasticsearch
  ports:
    - "5601:5601"
  environment:
    - XPACK_SECURITY_ENABLED=false
  restart: always

rabbitmq:
  container_name: rabbitmq
  image: tutum/rabbitmq
  ports:
    - "5672:5672"
    - "15672:15672"
  environment:
    - RABBITMQ_USER=username
    - RABBITMQ_PASS=password
  restart: always
